### PR TITLE
Remove accidentally committed non-code

### PR DESCRIPTION
**Pull request by jonahkichwacoders**
Files originally added in
8b6cd0443756a97a5a80e64da26fa1b8955a3e3b

Signed-off-by: Jonah Graham <jonah@kichwacoders.com>

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
@KasperGam I was wondering if you could review this PR. I assume, based on the contents, that these files were accidentally committed. Please let me know if I got something wrong.

**Comment by jonahkichwacoders** [comment]
A new/different PR is on the way with additional files that should have been part of this PR.

**Comment by jayjaybillings** [comment]
In your new PR, will you please document why these files need to be removed? Kasper is out this week and isn't a committer on the EAVP, so I'll have to look at it.

**Comment by jonahkichwacoders** [comment]
@jayjaybillings  Sure thing.

**Comment by jayjaybillings** [comment]
Ah, I see the problem now. Most of them are classes and other types of binary files.

**Comment by jayjaybillings** [comment]
Please cite #73 in your new PR.

**Pull request closed without merging**
